name = "fiori-test-prepper"
main = "worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# New static-assets config --------------------------
assets = { directory = "./public/", binding = "ASSETS" }
# or, equivalently:
# [assets]
# directory = "./public/"
# binding   = "ASSETS"
# ---------------------------------------------------
